import { z } from 'zod';

export const ParticipantsSchema = z.object({
  Participant_ID: z.number().int(),
  Red_Flag_Notes: z.string().max(254).nullable(),
  Contact_ID: z.number().int(),
  Participant_Type_ID: z.number().int(),
  Member_Status_ID: z.number().int().nullable(),
  Participant_Engagement_ID: z.number().int().nullable(),
  Participant_Start_Date: z.string().datetime(),
  Date_Joined: z.string().datetime().nullable(),
  Participant_End_Date: z.string().datetime().nullable(),
  Notes: z.string().max(1000).nullable(),
  Volunteer_Status_ID: z.number().int().nullable(),
  VIF_On_File: z.string().datetime().nullable(),
  AOV_Form_On_File: z.string().datetime().nullable(),
  Membership_Covenant: z.string().datetime().nullable(),
  Secure_Comments: z.boolean(),
  AOV_Exempt: z.boolean(),
  Connection_Meeting: z.string().datetime().nullable(),
  _First_Attendance_Ever: z.string().datetime().nullable(),
  _Second_Attendance_Ever: z.string().datetime().nullable(),
  _Third_Attendance_Ever: z.string().datetime().nullable(),
  _Last_Attendance_Ever: z.string().datetime().nullable(),
  Press_On_Letter_Sent: z.boolean().nullable(),
  New_Visitor_Follow_Up: z.string().max(25).nullable(),
  Campaign_Leaders_For_158: z.string().max(25).nullable(),
  _Background_Check_Type: z.string().max(128).nullable(),
  _Background_Check_Status: z.string().max(50).nullable(),
  _Background_Check_Date: z.string().datetime().nullable(),
  _Wait_To_Hold: z.string().datetime().nullable(),
  PCO_Connect_Mode: z.number().int().nullable(),
  Church_of_Record: z.number().int().nullable(),
  Baptism_Parish_Name: z.string().max(75).nullable(),
  Baptism_Parish_Address: z.string().max(254).nullable(),
  Birth_Certificate_Address: z.string().max(254).nullable(),
  Birth_Certificate_City: z.string().max(254).nullable(),
  Birth_Certificate_State: z.string().max(15).nullable(),
});

export type ParticipantsInput = z.infer<typeof ParticipantsSchema>;
