import { z } from 'zod';

export const PcoconnectPeopleSchema = z.object({
  PCOConnect_Person_ID: z.number().int(),
  Person_ID: z.number().int().nullable(),
  Participant_ID: z.number().int().nullable(),
  First_Name: z.string().max(50).nullable(),
  Middle_Name: z.string().max(50).nullable(),
  Last_Name: z.string().max(50).nullable(),
  Nickname: z.string().max(50).nullable(),
  Date_of_Birth: z.string().datetime().nullable(),
  Gender: z.string().max(15).nullable(),
  Email_Address: z.string().max(255).nullable(),
  Mobile_Phone: z.string().max(25).nullable(),
  Home_Phone: z.string().max(25).nullable(),
  Address_Line_1: z.string().max(75).nullable(),
  Address_Line_2: z.string().max(75).nullable(),
  City: z.string().max(50).nullable(),
  State_Region: z.string().max(50).nullable(),
  Postal_Code: z.string().max(25).nullable(),
  Anniversary_Date: z.string().datetime().nullable(),
  Status: z.string().max(50).nullable(),
  Membership: z.string().max(75).nullable(),
  Notes: z.string().max(2147483647).nullable(),
  Photo_URL: z.string().max(512).nullable(),
  Permissions: z.string().max(75).nullable(),
  Date_Last_Logged_In: z.string().datetime().nullable(),
  Date_Created: z.string().datetime().nullable(),
  Date_Updated: z.string().datetime().nullable(),
  Date_Refreshed: z.string().datetime().nullable(),
  Child: z.string().max(15).nullable(),
  Household_ID: z.number().int().nullable(),
  PCOConnect_Campus_ID: z.number().int().nullable(),
  Campus_ID: z.number().int().nullable(),
  Date_Inactivated: z.string().datetime().nullable(),
  Date_Archived: z.string().datetime().nullable(),
  Org_Num: z.number().int().nullable(),
});

export type PcoconnectPeopleInput = z.infer<typeof PcoconnectPeopleSchema>;
