import { z } from 'zod';

export const PocketPlatformAnalyticsSchema = z.object({
  Analytics_ID: z.number().int(),
  Analytics_GUID: z.string().max(255),
  Device_ID: z.string().max(128),
  User_ID: z.number().int().nullable(),
  Event_Type: z.string().max(100),
  Previous_Screen_Name: z.string().max(255).nullable(),
  Screen_Name: z.string().max(255),
  Analytics_Data: z.string().max(2147483647),
  Timestamp: z.string().datetime(),
  Platform: z.string().max(10),
  Screen_Size: z.string().max(120),
  OS_Version: z.string().max(12),
  Language: z.string().max(4),
  Event_ID: z.number().int().nullable(),
  Group_ID: z.number().int().nullable(),
  Opportunity_ID: z.number().int().nullable(),
  Sermon_ID: z.number().int().nullable(),
  Sermon_Series_ID: z.number().int().nullable(),
  GCE_ID: z.number().int().nullable(),
  Form_ID: z.number().int().nullable(),
  Journey_ID: z.number().int().nullable(),
  Milestone_ID: z.number().int().nullable(),
  Reading_Plan_ID: z.number().int().nullable(),
  Reading_Plan_Day_ID: z.number().int().nullable(),
  Dashboard_Item_ID: z.string().max(150).nullable(),
  Dashboard_Display_Name: z.string().max(255).nullable(),
  Dashboard_Item_Content: z.string().max(2147483647).nullable(),
  Webview_URL: z.string().max(1000).nullable(),
  Summarized: z.boolean(),
  Metric_ID: z.number().int().nullable(),
  Contact_Display_Name: z.string().max(255).nullable(),
  Event_Title: z.string().max(255).nullable(),
  Form_Title: z.string().max(255).nullable(),
  GCE_Title: z.string().max(255).nullable(),
  Group_Name: z.string().max(255).nullable(),
  Journey_Name: z.string().max(255).nullable(),
  Milestone_Title: z.string().max(255).nullable(),
  Opportunity_Title: z.string().max(255).nullable(),
  Reading_Plan_Day_Name: z.string().max(255).nullable(),
  Reading_Plan_Name: z.string().max(255).nullable(),
  Sermon_Series_Title: z.string().max(255).nullable(),
  Sermon_Title: z.string().max(255).nullable(),
  App_ID: z.number().int().nullable(),
  App_Slug: z.string().max(200).nullable(),
});

export type PocketPlatformAnalyticsInput = z.infer<typeof PocketPlatformAnalyticsSchema>;
