import { z } from 'zod';

export const SurgeChurchPlantsSchema = z.object({
  Surge_Church_Plant_ID: z.number().int(),
  Program_ID: z.number().int(),
  Church_Plant_Cost: z.number(),
  Surge_Category_ID: z.number().int(),
  Strategic_Church_Plant: z.boolean(),
  Household_ID: z.number().int().nullable(),
  Group_ID: z.number().int().nullable(),
  Prayer_Partner_Group_ID: z.number().int().nullable(),
  External_Plant_Number: z.string().max(50).nullable(),
  Identity_Protected: z.boolean(),
  Church_Plant_Pastor: z.string().max(50).nullable(),
  Church_Plant_Date: z.string().datetime().nullable(),
  Church_Plant_Partner: z.number().int().nullable(),
  City_or_Village: z.string().max(50).nullable(),
  State_or_Region: z.string().max(50).nullable(),
  Country_ID: z.number().int().nullable(),
  Continent_ID: z.number().int().nullable(),
  Church_Plant_Notes: z.string().max(2000).nullable(),
  Invoice_Number: z.string().max(50).nullable(),
  Invoice_Date: z.string().datetime().nullable(),
  Check_Sent_to_Surge: z.string().datetime().nullable(),
  Check_Number: z.string().max(50).nullable(),
  Funded_Message: z.number().int().nullable(),
  Funded_Template: z.number().int(),
  Funded_Message_Date: z.string().datetime().nullable(),
  _Funded_Message_Sent: z.boolean(),
  Certificate_Received_From_Surge: z.string().datetime().nullable(),
  Certificate_Sent_to_Donor: z.boolean(),
  Certificate_Message: z.number().int().nullable(),
  Certificate_Template: z.number().int(),
  Certificate_Message_Date: z.string().datetime().nullable(),
  _Certificate_Message_Sent: z.boolean(),
  Placard_Number: z.number().int().nullable(),
  Placard_Chair: z.string().max(5).nullable(),
  Placard_Message: z.number().int().nullable(),
  Placard_Template: z.number().int(),
  Placard_Message_Date: z.string().datetime().nullable(),
  _Placard_Message_Sent: z.boolean(),
  Latitude: z.string().max(15).nullable(),
  Longitude: z.string().max(15).nullable(),
  OLG_Surge_Subfund: z.string().max(100).nullable(),
  Church_Plant_Multiplier: z.number().int(),
  Parent_Church_Plant: z.number().int().nullable(),
});

export type SurgeChurchPlantsInput = z.infer<typeof SurgeChurchPlantsSchema>;
